default_target_url: "https://monzo.com"

logger:
  # debug_level: true
  debug_level: false

crawler:
  throttling: 50ms

printer:
  context_timeout: 10s

http:
  timeout: 60s
  max_idle_conns: 10
  max_idle_conns_per_host: 10
  idle_conn_timeout: 30s